# Generated by Django 4.1.4 on 2022-12-09 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='donhang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluong', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='giohang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaymua', models.DateTimeField(auto_now=True)),
                ('trangthai', models.BooleanField(default=False)),
                ('sanphams', models.ManyToManyField(related_name='sanphams', through='core.donhang', to='core.sanpham')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='donhang',
            name='giohang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donhangs', to='core.giohang'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='sanpham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donhangs', to='core.sanpham'),
        ),
    ]
