# Generated by Django 4.1.4 on 2022-12-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_giohang_diachi_alter_sanpham_mota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giohang',
            name='sanphams',
            field=models.ManyToManyField(related_name='sanphams', related_query_name='soluong', through='core.donhang', to='core.sanpham'),
        ),
    ]
