# Generated by Django 4.1.4 on 2022-12-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_giohang_sanphams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giohang',
            name='diachi',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='sanphams',
            field=models.ManyToManyField(related_name='sanphams', through='core.donhang', to='core.sanpham'),
        ),
    ]
